import Assets from "./constants/Assets";

export const priceDesc = [
  {
    title: "Aval qty",
    img: Assets.starr,
    price: 1000,
  },
  {
    title: "Price per unit",
    img: Assets.starr,
    price: 1000,
  },
  {
    title: "Total price",
    img: Assets.starr,
    price: 1000,
  },
];

export const orderItems = [
  {
    status: `Today's Order`,
    price: 53000,
    img: Assets.cart,
  },
  {
    status: `Pending`,
    price: 120000,
    img: Assets.cart,
  },
  {
    status: `Cancelled`,
    price: 53,
    img: Assets.cart,
  },
  {
    status: `Volume`,
    price: 53000,
    img: Assets.cart,
  },
];

export const drugs = [
  {
    productNo: "0125485647",
    cover: Assets.lokmal,
    productName: "Lokmal Malaria",
    merchantName: "Tunde Orioza",
    qty: 100,
    price: "10,000",
    dateCreated: "20/12/2563 14:20:44",
    status: "Paid",
  },
  {
    productNo: "0125485647",
    cover: Assets.lokmal,
    productName: "Lokmal Malaria",
    merchantName: "Tunde Orioza",
    qty: 100,
    price: "10,000",
    dateCreated: "20/12/2563 14:20:44",
    status: "5days deferral",
  },
  {
    productNo: "0125485647",
    cover: Assets.lokmal,
    productName: "Lokmal Malaria",
    merchantName: "Tunde Orioza",
    qty: 100,
    price: "10,000",
    dateCreated: "20/12/2563 14:20:44",
    status: "Paid",
  },
  {
    productNo: "0125485647",
    cover: Assets.lokmal,
    productName: "Lokmal Malaria",
    merchantName: "Tunde Orioza",
    qty: 100,
    price: "10,000",
    dateCreated: "20/12/2563 14:20:44",
    status: "5days deferral",
  },
  {
    productNo: "0125485647",
    cover: Assets.lokmal,
    productName: "Lokmal Malaria",
    merchantName: "Tunde Orioza",
    qty: 100,
    price: "10,000",
    dateCreated: "20/12/2563 14:20:44",
    status: "Canceled",
  },
];

export const merchants = [
  { value: "all", label: "All" },
  { value: "merchant1", label: "Merchant 1" },
  { value: "merchant2", label: "Merchant 2" },
  { value: "merchant3", label: "Merchant 3" },
];

export const statuses = [
  { value: "all", label: "All" },
  { value: "completed", label: "Completed" },
  { value: "pending", label: "Pending" },
  { value: "cancelled", label: "Cancelled" },
];

export const dates = [
  { value: "today", label: "Today" },
  { value: "yesterday", label: "Yesterday" },
  { value: "last7days", label: "Last 7 Days" },
  { value: "last30days", label: "Last 30 Days" },
];

export const salesData = [
  { day: "MO", value: 30 },
  { day: "TU", value: 40 },
  { day: "WE", value: 50 },
  { day: "TH", value: 35 },
  { day: "FR", value: 20 },
  { day: "SA", value: 45 },
  { day: "SU", value: 62 },
];

export const orderTable = [
  {
    avatar: Assets.avatar,
    distributor: "Tunde Oriza",
    date: "21 July",
    product: "Lotam",
    qty: "200",
    prize: "N14,000",
    status: "New",
    Action: Assets.green,
  },
  {
    avatar: Assets.avatar,
    distributor: "Tunde Oriza",
    date: "21 July",
    product: "Lotam",
    qty: "200",
    prize: "N14,000",
    status: "New",
    Action: Assets.red,
  },
  {
    avatar: Assets.avatar,
    distributor: "Tunde Oriza",
    date: "21 July",
    product: "Lotam",
    qty: "200",
    prize: "N14,000",
    status: "New",
    Action: Assets.green,
  },
  {
    avatar: Assets.avatar,
    distributor: "Tunde Oriza",
    date: "21 July",
    product: "Lotam",
    qty: "200",
    prize: "N14,000",
    status: "New",
    Action: Assets.red,
  },
  {
    avatar: Assets.avatar,
    distributor: "Tunde Oriza",
    date: "21 July",
    product: "Lotam",
    qty: "200",
    prize: "N14,000",
    status: "New",
    Action: Assets.green,
  },
  {
    avatar: Assets.avatar,
    distributor: "Tunde Oriza",
    date: "21 July",
    product: "Lotam",
    qty: "200",
    prize: "N14,000",
    status: "New",
    Action: Assets.green,
  },
  {
    avatar: Assets.avatar,
    distributor: "Tunde Oriza",
    date: "21 July",
    product: "Lotam",
    qty: "200",
    prize: "N14,000",
    status: "New",
    Action: Assets.green,
  },
];

export const headers = [
  "Distributor",
  "Date",
  "Product",
  "Qty",
  "Prize",
  "Status",
  "Action",
];

export const orders = [
  {
    company: "C1k567891078",
    date: "21 July",
    product: "Lotam",
    qty: 200,
    price: "₦14,000",
    status: "Approved",
    statusClass: "success",
  },
  {
    company: "C1k567891078",
    date: "21 July",
    product: "Lotam",
    qty: 200,
    price: "₦14,000",
    status: "Approved",
    statusClass: "success",
  },
  {
    company: "C1k567891078",
    date: "21 July",
    product: "Lotam",
    qty: 200,
    price: "₦14,000",
    status: "Pending",
    statusClass: "warning",
  },
  {
    company: "C1k567891078",
    date: "21 July",
    product: "Lotam",
    qty: 200,
    price: "₦14,000",
    status: "Approved",
    statusClass: "success",
  },
  {
    company: "C1k567891078",
    date: "21 July",
    product: "Lotam",
    qty: 200,
    price: "₦14,000",
    status: "Approved",
    statusClass: "success",
  },
];

export const partners = [
  {
    number: "20,000",
    details: "View Details",
  },
  {
    number: "20,000",
    details: "View Details",
  },
  {
    number: "20,000",
    details: "View Details",
  },
  {
    number: "20,000",
    details: "View Details",
  },
  {
    number: "20,000",
    details: "View Details",
  },
  {
    number: "20,000",
    details: "View Details",
  },
];

export const transaction = [
  {
    id: 1,
    icon: Assets.arrowRight,
    title: " Payment to Emzor",
    date: " Today, 26th Sept at 3:am",
    price: "50,000,00",
    img: Assets.approve,
    status: "Success",
  },
  {
    id: 2,
    icon: Assets.arrowLeft,
    title: " Withdrawal",
    date: " Today, 26th Sept at 3:am",
    price: "50,000,00",
    img: Assets.approve,
    status: "Success",
  },
  {
    id: 3,
    icon: Assets.arrowRight,
    title: " Payment to Emzor",
    date: " Today, 26th Sept at 3:am",
    price: "50,000,00",
    img: Assets.decline,
    status: "Decline",
  },
  {
    id: 4,
    icon: Assets.arrowRight,
    title: " Payment to Emzor",
    date: " Today, 26th Sept at 3:am",
    price: "50,000,00",
    img: Assets.pending,
    status: "Pending",
  },
];

export const faqs = [
  {
    question: "How do Tickets get resolved",
    answer:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    question: "How do Tickets get resolved",
    answer:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    question: "How do Tickets get resolved",
    answer:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
];

export const documents = [
  {
    title: "Certificate of incorporation ",
    text: "Upload file",
  },
  {
    title: "Copy of certificate of Memorandom ",
    text: "Upload file",
  },
  {
    title: "Copy of form Co7 or CAC 2.3 (Particulars of Director) CAC 1.1 ",
    text: "Upload file",
  },

  {
    title: "TIN  Certificate",
    text: "Upload file",
  },

  {
    title: "Board Resolution or Mandate letter ",
    text: "Upload file",
  },
  {
    title: "Valid means of ID ",
    text: "Upload file",
  },
  {
    title: "Evidence of business Address ",
    text: "Upload file",
  },
  {
    title: " Residence Permit ",
    text: "Upload file",
  },
  {
    title: " SCUML Certificate",
    text: "Upload file",
  },
  {
    title: "Draft Agreement",
    text: "Upload file",
  },
  {
    title: "AML Policy ",
    text: "Upload file",
  },
];

export const stateData = {
  Nigeria: [
    "Abia",
    "Adamawa",
    "Akwa Ibom",
    "Anambra",
    "Bauchi",
    "Bayelsa",
    "Benue",
    "Borno",
    "Cross River",
    "Delta",
    "Ebonyi",
    "Edo",
    "Ekiti",
    "Enugu",
    "FCT",
    "Gombe",
    "Imo",
    "Jigawa",
    "Kaduna",
    "Kano",
    "Katsina",
    "Kebbi",
    "Kogi",
    "Kwara",
    "Lagos",
    "Nasarawa",
    "Niger",
    "Ogun",
    "Ondo",
    "Osun",
    "Oyo",
    "Plateau",
    "Rivers",
    "Sokoto",
    "Taraba",
    "Yobe",
    "Zamfara",
  ],
};

export const localGovtData = {
  Abia: [
    "Aba North",
    "Aba South",
    "Arochukwu",
    "Bende",
    "Ikwuano",
    "Isiala Ngwa North",
    "Isiala Ngwa South",
    "Isuikwuato",
    "Obi Ngwa",
    "Ohafia",
    "Osisioma",
    "Ugwunagbo",
    "Ukwa East",
    "Ukwa West",
    "Umuahia North",
    "Umuahia South",
    "Umu Nneochi",
  ],
  Adamawa: [
    "Demsa",
    "Fufore",
    "Ganye",
    "Girei",
    "Gombi",
    "Guyuk",
    "Hong",
    "Jada",
    "Lamurde",
    "Madagali",
    "Maiha",
    "Mayo Belwa",
    "Michika",
    "Mubi North",
    "Mubi South",
    "Numan",
    "Shelleng",
    "Song",
    "Toungo",
    "Yola North",
    "Yola South",
  ],
  AkwaIbom: [
    "Abak",
    "Eastern Obolo",
    "Eket",
    "Esit Eket",
    "Essien Udim",
    "Etim Ekpo",
    "Etinan",
    "Ibeno",
    "Ibesikpo Asutan",
    "Ibiono-Ibom",
    "Ika",
    "Ikono",
    "Ikot Abasi",
    "Ikot Ekpene",
    "Ini",
    "Itu",
    "Mbo",
    "Mkpat-Enin",
    "Nsit-Atai",
    "Nsit-Ibom",
    "Nsit-Ubium",
    "Obot Akara",
    "Okobo",
    "Onna",
    "Oron",
    "Oruk Anam",
    "Udung-Uko",
    "Ukanafun",
    "Uruan",
    "Urue-Offong/Oruko",
    "Uyo",
  ],
  Anambra: [
    "Aguata",
    "Anambra East",
    "Anambra West",
    "Anaocha",
    "Awka North",
    "Awka South",
    "Ayamelum",
    "Dunukofia",
    "Ekwusigo",
    "Idemili North",
    "Idemili South",
    "Ihiala",
    "Njikoka",
    "Nnewi North",
    "Nnewi South",
    "Ogbaru",
    "Onitsha North",
    "Onitsha South",
    "Orumba North",
    "Orumba South",
    "Oyi",
  ],
  Bauchi: [
    "Alkaleri",
    "Bauchi",
    "Bogoro",
    "Damban",
    "Darazo",
    "Dass",
    "Gamawa",
    "Ganjuwa",
    "Giade",
    "Itas/Gadau",
    "Jama'are",
    "Katagum",
    "Kirfi",
    "Misau",
    "Ningi",
    "Shira",
    "Tafawa Balewa",
    "Toro",
    "Warji",
    "Zaki",
  ],
  Bayelsa: [
    "Brass",
    "Ekeremor",
    "Kolokuma/Opokuma",
    "Nembe",
    "Ogbia",
    "Sagbama",
    "Southern Ijaw",
    "Yenagoa",
  ],
  Benue: [
    "Ado",
    "Agatu",
    "Apa",
    "Buruku",
    "Gboko",
    "Guma",
    "Gwer East",
    "Gwer West",
    "Katsina-Ala",
    "Konshisha",
    "Kwande",
    "Logo",
    "Makurdi",
    "Obi",
    "Ogbadibo",
    "Ohimini",
    "Oju",
    "Okpokwu",
    "Otukpo",
    "Tarka",
    "Ukum",
    "Ushongo",
    "Vandeikya",
  ],
  Borno: [
    "Abadam",
    "Askira/Uba",
    "Bama",
    "Bayo",
    "Biu",
    "Chibok",
    "Damboa",
    "Dikwa",
    "Gubio",
    "Guzamala",
    "Gwoza",
    "Hawul",
    "Jere",
    "Kaga",
    "Kala/Balge",
    "Konduga",
    "Kukawa",
    "Kwaya Kusar",
    "Mafa",
    "Magumeri",
    "Maiduguri",
    "Marte",
    "Mobbar",
    "Monguno",
    "Ngala",
    "Nganzai",
    "Shani",
  ],
  CrossRiver: [
    "Abi",
    "Akamkpa",
    "Akpabuyo",
    "Bakassi",
    "Bekwarra",
    "Biase",
    "Boki",
    "Calabar Municipal",
    "Calabar South",
    "Etung",
    "Ikom",
    "Obanliku",
    "Obubra",
    "Obudu",
    "Odukpani",
    "Ogoja",
    "Yakuur",
    "Yala",
  ],
  Delta: [
    "Aniocha North",
    "Aniocha South",
    "Bomadi",
    "Burutu",
    "Ethiope East",
    "Ethiope West",
    "Ika North East",
    "Ika South",
    "Isoko North",
    "Isoko South",
    "Ndokwa East",
    "Ndokwa West",
    "Okpe",
    "Oshimili North",
    "Oshimili South",
    "Patani",
    "Sapele",
    "Udu",
    "Ughelli North",
    "Ughelli South",
    "Ukwuani",
    "Uvwie",
    "Warri North",
    "Warri South",
    "Warri South West",
  ],
  Ebonyi: [
    "Abakaliki",
    "Afikpo North",
    "Afikpo South (Edda)",
    "Ebonyi",
    "Ezza North",
    "Ezza South",
    "Ikwo",
    "Ishielu",
    "Ivo",
    "Izzi",
    "Ohaozara",
    "Ohaukwu",
    "Onicha",
  ],
  Edo: [
    "Akoko-Edo",
    "Egor",
    "Esan Central",
    "Esan North-East",
    "Esan South-East",
    "Esan West",
    "Etsako Central",
    "Etsako East",
    "Etsako West",
    "Igueben",
    "Ikpoba-Okha",
    "Orhionmwon",
    "Oredo",
    "Ovia North-East",
    "Ovia South-West",
    "Owan East",
    "Owan West",
    "Uhunmwonde",
  ],
  Ekiti: [
    "Ado Ekiti",
    "Efon",
    "Ekiti East",
    "Ekiti South-West",
    "Ekiti West",
    "Emure",
    "Gbonyin",
    "Ido Osi",
    "Ijero",
    "Ikere",
    "Ikole",
    "Ilejemeje",
    "Irepodun/Ifelodun",
    "Ise/Orun",
    "Moba",
    "Oye",
  ],
  Enugu: [
    "Aninri",
    "Awgu",
    "Enugu East",
    "Enugu North",
    "Enugu South",
    "Ezeagu",
    "Igbo Etiti",
    "Igbo Eze North",
    "Igbo Eze South",
    "Isi Uzo",
    "Nkanu East",
    "Nkanu West",
    "Nsukka",
    "Oji River",
    "Udenu",
    "Udi",
    "Uzo-Uwani",
  ],
  FCT: [
    "Abaji",
    "Bwari",
    "Gwagwalada",
    "Kuje",
    "Kwali",
    "Municipal Area Council",
  ],
  Gombe: [
    "Akko",
    "Balanga",
    "Billiri",
    "Dukku",
    "Funakaye",
    "Gombe",
    "Kaltungo",
    "Kwami",
    "Nafada",
    "Shongom",
    "Yamaltu/Deba",
  ],
  Imo: [
    "Aboh Mbaise",
    "Ahiazu Mbaise",
    "Ehime Mbano",
    "Ezinihitte",
    "Ideato North",
    "Ideato South",
    "Ihitte/Uboma",
    "Ikeduru",
    "Isiala Mbano",
    "Isu",
    "Mbaitoli",
    "Ngor Okpala",
    "Njaba",
    "Nkwerre",
    "Nwangele",
    "Obowo",
    "Oguta",
    "Ohaji/Egbema",
    "Okigwe",
    "Orlu",
    "Orsu",
    "Oru East",
    "Oru West",
    "Owerri Municipal",
    "Owerri North",
    "Owerri West",
  ],
  Jigawa: [
    "Auyo",
    "Babura",
    "Biriniwa",
    "Birnin Kudu",
    "Buji",
    "Dutse",
    "Gagarawa",
    "Garki",
    "Gumel",
    "Guri",
    "Gwaram",
    "Gwiwa",
    "Hadejia",
    "Jahun",
    "Kafin Hausa",
    "Kaugama",
    "Kazaure",
    "Kiri Kasama",
    "Kiyawa",
    "Maigatari",
    "Malam Madori",
    "Miga",
    "Ringim",
    "Roni",
    "Sule Tankarkar",
    "Taura",
  ],
};
